### ISSUE TITLE
Update milestones and labels to reflect principles

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/learning-os#185]
### Context

_Briefly describe the context for this issue. What is the core question or feature that it addresses? Why is it important?_

The milestones and labels are a little outdated and need some refreshing.
### Criteria

_Define the success criteria for this issue. What must an acceptable solution include?_
- [x] All milestones are relevant and accurate
- [x] All labels are relevant and accurate
### Principles razor

_In order for an issue to be marked as `passing`, the proposed solution must be aligned with our principles. Check off the principles that this solution is consistent with._
- [x] Cultivate a learning community.
- [x] Prioritize scale over quality
- [x] Align incentives
- [x] Build a team game
- [x] Trust people's intentions and potential
- [x] Enable self-organization & self-determination
- [x] Map feedback loops
- [x] Optimize for agility
- [x] Simulation not preparation
- [x] Sustain the tension between individual and collective gain
