### ISSUE TITLE
Harvest work to close past-due milestones

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/learning-os#194]
### Context

We've gone past our deadlines for several milestones, but this is mostly because the work hasn't been captured and associated with the milestone.
### Criteria
- [x] For each overdue milestone, find/create issues to get it to completion
- [x] Add completed work to these issues
- [x] Move all issues related to overdue milestones into review
